/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Limit = number
export type Offset = number
export type Start = (string | null)
export type End = (string | null)
export type Success = boolean
export type Message = string
export type Error = string
export type Timestamp = string
export type Activityid = string
export type Version = number
export type Limit1 = number
export type Success1 = boolean
export type Activities = {
[k: string]: unknown
}[]
export type Count = number
export type Maxversion = number
export type Success2 = boolean
export type Totaldates = number
export type Totalactivities = number
export type Error1 = string
export type Activityid1 = string
export type Success3 = boolean
export type Message1 = string
export type Error2 = string
export type Id = string
export type Title = string
export type Description = string
export type Starttime = string
export type Endtime = string
export type Sourceactionids = string[]
export type Createdat = string
export type Events = EventResponse[]
export type Activityid2 = string
export type Success4 = boolean
export type Message2 = string
export type Error3 = string
export type Timestamp1 = string
export type Startdate = string
export type Enddate = string
export type Activityids = string[]
export type Mergedtitle = string
export type Mergeddescription = string
export type Success5 = boolean
export type Message3 = string
export type Error4 = string
export type Mergedactivityid = string
export type Activityid3 = string
export type Title1 = string
export type Description1 = string
export type Eventindexes = number[]
export type Splitpoints = SplitPoint[]
export type Success6 = boolean
export type Message4 = string
export type Error5 = string
export type Newactivityids = string[]
export type Activityid4 = string
export type Dimension = string
export type Rating = number
export type Note = (string | null)
export type Success7 = boolean
export type Message5 = string
export type Error6 = string
export type Id1 = string
export type Activityid5 = string
export type Dimension1 = string
export type Rating1 = number
export type Note1 = (string | null)
export type Createdat1 = string
export type Updatedat = string
export type Timestamp2 = string
export type Activityid6 = string
export type Success8 = boolean
export type Message6 = string
export type Error7 = string
export type Data2 = (ActivityRatingData[] | null)
export type Timestamp3 = string
export type Activityid7 = string
export type Dimension2 = string
export type Agent = string
export type Plandescription = string
export type Success9 = boolean
export type Message7 = string
export type Error8 = string
export type Data3 = ({
[k: string]: unknown
} | {
[k: string]: unknown
}[] | null)
export type Taskid = string
export type Taskid1 = string
export type Limit2 = number
export type Status = (string | null)
export type Taskid2 = string
export type Scheduleddate = string
export type Taskid3 = string
export type Scheduleddate1 = string
export type Taskid4 = string
export type Conversationid = (string | null)
export type Title2 = string
export type Relatedactivityids = (string[] | null)
export type Metadata = ({
[k: string]: unknown
} | null)
export type Modelid = (string | null)
export type Activityids1 = string[]
export type Conversationid1 = string
export type Content = string
export type Images = (string[] | null)
export type Modelid1 = (string | null)
export type Limit3 = (number | null)
export type Offset1 = (number | null)
export type Conversationid2 = string
export type Limit4 = (number | null)
export type Offset2 = (number | null)
export type Conversationid3 = string
export type Conversationids = (string[] | null)
export type Conversationid4 = string
export type Success10 = boolean
export type Message8 = string
export type Error9 = string
export type Data4 = ({
[k: string]: unknown
} | null)
export type Enabled = (boolean | null)
export type Interval = (number | null)
export type Datawindow = (number | null)
export type Enablesystemnotification = (boolean | null)
export type Enablelive2Ddisplay = (boolean | null)
export type Limit5 = number
export type Offset3 = number
export type Enabled1 = (boolean | null)
export type Selectedmodelurl = (string | null)
export type Modeldir = (string | null)
export type Remotemodels = (string[] | null)
export type Notificationduration = (number | null)
export type Limit6 = number
export type Eventtype = (string | null)
export type Starttime1 = (string | null)
export type Endtime1 = (string | null)
export type Eventid = string
export type Eventid1 = string
export type Success11 = boolean
export type Message9 = string
export type Error10 = string
export type Id2 = string
export type Title3 = string
export type Description2 = string
export type Keywords = string[]
export type Timestamp4 = string
export type Screenshots = string[]
export type Createdat2 = string
export type Actions = ActionResponse[]
export type Eventid2 = string
export type Limit7 = number
export type Offset4 = number
export type Id3 = string
export type Id4 = string
export type Success12 = boolean
export type Message10 = string
export type Error11 = string
export type Id5 = string
export type Title4 = string
export type Description3 = string
export type Keywords1 = string[]
export type Createdat3 = (string | null)
export type Sourceactionid = (string | null)
export type Favorite = boolean
export type Deleted = boolean
export type Timestamp5 = string
export type Title5 = string
export type Description4 = string
export type Keywords2 = string[]
export type Success13 = boolean
export type Message11 = string
export type Error12 = string
export type Timestamp6 = string
export type Includecompleted = boolean
export type Todoid = string
export type Scheduleddate2 = string
export type Scheduledtime = (string | null)
export type Scheduledendtime = (string | null)
export type Recurrencerule = ({
[k: string]: unknown
} | null)
export type Todoid1 = string
export type Date = string
export type Success14 = boolean
export type Message12 = string
export type Error13 = string
export type Id6 = string
export type Date1 = string
export type Content1 = string
export type Sourceactivityids = string[]
export type Createdat4 = string
export type Timestamp7 = string
export type Limit8 = number
export type Success15 = boolean
export type Message13 = string
export type Error14 = string
export type Diaries = DiaryData[]
export type Count1 = number
export type Timestamp8 = string
export type Success16 = boolean
export type Message14 = string
export type Error15 = string
export type Timestamp9 = string
export type Intervalseconds = (number | null)
export type Monitorindex = number
export type Monitorname = string
export type Isenabled = boolean
export type Resolution = string
export type Isprimary = boolean
export type Screens = ScreenSetting[]
export type Keyboardenabled = (boolean | null)
export type Mouseenabled = (boolean | null)
export type Limit9 = number
export type Eventtype1 = (string | null)
export type Starttime2 = (string | null)
export type Endtime2 = (string | null)
export type Allgranted = boolean
/**
 * Permission type enumeration
 */
export type PermissionType = ("accessibility" | "screen_recording")
/**
 * Permission status
 */
export type PermissionStatus = ("granted" | "denied" | "not_determined" | "restricted")
export type Name = string
export type Description5 = string
export type Required = boolean
export type Systemsettingspath = string
export type Platform = string
export type Needsrestart = boolean
export type Success17 = boolean
export type Message15 = string
export type Error16 = string
export type Success18 = boolean
export type Message16 = string
export type Error17 = string
export type Granted = (boolean | null)
export type Delayseconds = number
export type Success19 = boolean
export type Message17 = string
export type Error18 = string
export type Delayseconds1 = (number | null)
export type Timestamp10 = string
export type Userintent = string
export type Durationminutes = number
export type Associatedtodoid = (string | null)
export type Workdurationminutes = number
export type Breakdurationminutes = number
export type Totalrounds = number
export type Success20 = boolean
export type Message18 = string
export type Error19 = string
export type Sessionid = string
export type Userintent1 = string
export type Starttime3 = string
export type Elapsedminutes = number
export type Planneddurationminutes = number
export type Associatedtodoid1 = (string | null)
export type Associatedtodotitle = (string | null)
export type Workdurationminutes1 = number
export type Breakdurationminutes1 = number
export type Totalrounds1 = number
export type Currentround = number
export type Currentphase = ("work" | "break" | "completed")
export type Phasestarttime = (string | null)
export type Completedrounds = number
export type Remainingphaseseconds = (number | null)
export type Pureworkdurationminutes = number
export type Timestamp11 = string
export type Status1 = string
export type Success21 = boolean
export type Message19 = string
export type Error20 = string
export type Sessionid1 = string
export type Processingjobid = (string | null)
export type Rawrecordscount = number
export type Message20 = string
export type Timestamp12 = string
export type Success22 = boolean
export type Message21 = string
export type Error21 = string
export type Timestamp13 = string
export type Sessionid2 = string
export type Workphase = number
export type Sessionid3 = string
export type Success23 = boolean
export type Message22 = string
export type Error22 = string
export type Timestamp14 = string
export type Id7 = string
export type Title6 = string
export type Starttime4 = string
export type Endtime3 = string
export type Sessiondurationminutes = number
export type Activities1 = UnlinkedActivityData[]
export type Sessionid4 = string
export type Activityids2 = string[]
export type Success24 = boolean
export type Message23 = string
export type Error23 = string
export type Timestamp15 = string
export type Linkedcount = number
export type Success25 = boolean
export type Message24 = string
export type Error24 = string
export type Id8 = string
export type Name1 = string
export type Description6 = string
export type Workdurationminutes2 = number
export type Breakdurationminutes2 = number
export type Totalrounds2 = number
export type Icon = string
export type Data7 = PomodoroPreset[]
export type Timestamp16 = string
export type Date2 = string
export type Success26 = boolean
export type Message25 = string
export type Error25 = string
export type Date3 = string
export type Completedcount = number
export type Totalfocusminutes = number
export type Averagedurationminutes = number
export type Sessions = {
[k: string]: unknown
}[]
export type Timestamp17 = string
export type Sessionid5 = string
export type Success27 = boolean
export type Message26 = string
export type Error26 = string
export type Id9 = string
export type Title7 = string
export type Description7 = string
export type Starttime5 = string
export type Endtime4 = string
export type Sessiondurationminutes1 = number
export type Workphase1 = (number | null)
export type Focusscore = (number | null)
export type Topictags = string[]
export type Sourceeventids = string[]
export type Sourceactionids1 = string[]
export type Aggregationmode = string
export type Activities2 = PomodoroActivityData[]
export type Overallfocusscore = number
export type Activitycount = number
export type Topicdiversity = number
export type Averageactivityduration = number
export type Focuslevel = string
export type Focusscore1 = number
export type Focuslevel1 = string
export type Topicconsistency = number
export type Durationdepth = number
export type Switchingrhythm = number
export type Workquality = number
export type Goalorientation = number
export type Strengths = string[]
export type Weaknesses = string[]
export type Suggestions = string[]
export type Worktype = string
export type Isfocusedwork = boolean
export type Distractionpercentage = number
export type Deepworkminutes = number
export type Contextsummary = string
export type Phasetype = ("work" | "break")
export type Phasenumber = number
export type Starttime6 = string
export type Endtime5 = string
export type Durationminutes1 = number
export type Phasetimeline = PhaseTimelineItem[]
export type Timestamp18 = string
export type Period = string
export type Referencedate = (string | null)
export type Success28 = boolean
export type Message27 = string
export type Error27 = string
export type Period1 = string
export type Startdate1 = string
export type Enddate1 = string
export type Weeklytotal = number
export type Focushours = number
export type Dailyaverage = number
export type Completionrate = number
export type Day = string
export type Date4 = string
export type Sessions1 = number
export type Minutes = number
export type Dailydata = DailyFocusData[]
export type Timestamp19 = string
export type Sessionid6 = string
export type Success29 = boolean
export type Message28 = string
export type Error28 = string
export type Sessionid7 = string
export type Deletedactivitiescount = number
export type Timestamp20 = string
export type Days = number
export type Startdate2 = string
export type Enddate2 = string
export type Startdate3 = string
export type Enddate3 = string
export type Startdate4 = string
export type Enddate4 = string
export type Success30 = boolean
export type Message29 = string
export type Error29 = string
export type Stats = ({
[k: string]: unknown
} | null)
export type Hashes = string[]
export type Success31 = boolean
export type Message30 = string
export type Error30 = string
export type Foundcount = number
export type Requestedcount = number
export type Maxagehours = number
export type Success32 = boolean
export type Message31 = string
export type Error31 = string
export type Cleanedcount = number
export type Success33 = boolean
export type Message32 = string
export type Error32 = string
export type Clearedcount = number
export type Success34 = boolean
export type Message33 = string
export type Error33 = string
export type Enabled2 = boolean
export type Strategy = string
export type Phashthreshold = number
export type Mininterval = number
export type Enablecontentanalysis = boolean
export type Enabletextdetection = boolean
export type Timestamp21 = string
export type Success35 = boolean
export type Message34 = string
export type Error34 = string
export type Stats1 = ({
[k: string]: unknown
} | null)
export type Config = ({
[k: string]: unknown
} | null)
export type Enabled3 = (boolean | null)
export type Strategy1 = (string | null)
export type Phashthreshold1 = (number | null)
export type Mininterval1 = (number | null)
export type Maximages = (number | null)
export type Enablecontentanalysis1 = (boolean | null)
export type Enabletextdetection1 = (boolean | null)
export type Success36 = boolean
export type Message35 = string
export type Error35 = string
export type Timestamp22 = string
export type Filepath = string
export type Success37 = boolean
export type Message36 = string
export type Error36 = string
export type Dataurl = string
export type Success38 = boolean
export type Message37 = string
export type Error37 = string
export type Totalactions = number
export type Actionswithscreenshots = number
export type Actionsallimagesok = number
export type Actionspartialmissing = number
export type Actionsallmissing = number
export type Totalimagereferences = number
export type Imagesfound = number
export type Imagesmissing = number
export type Missingratepercent = number
export type Memorycachecurrentsize = number
export type Memorycachemaxsize = number
export type Memoryttlseconds = number
export type Actionswithissues = {
[k: string]: unknown
}[]
export type Strategy2 = ("delete_actions" | "remove_references" | "dry_run")
export type Actionids = (string[] | null)
export type Success39 = boolean
export type Message38 = string
export type Error38 = string
export type Actionsprocessed = number
export type Actionsdeleted = number
export type Referencesremoved = number
export type Imagesremoved = number
export type Name2 = string
/**
 * Provider identifier
 */
export type Provider = (string | null)
export type Apiurl = string
export type Model = string
export type Inputtokenprice = number
export type Outputtokenprice = number
export type Currency = string
export type Apikey = string
export type Success40 = boolean
export type Message39 = string
export type Error39 = string
export type Data8 = ({
[k: string]: unknown
} | {
[k: string]: unknown
}[] | null)
export type Timestamp23 = (string | null)
export type Modelid2 = string
export type Name3 = (string | null)
export type Apiurl1 = (string | null)
export type Model1 = (string | null)
export type Inputtokenprice1 = (number | null)
export type Outputtokenprice1 = (number | null)
/**
 * Provider identifier
 */
export type Provider1 = (string | null)
export type Currency1 = (string | null)
export type Apikey1 = (string | null)
export type Modelid3 = string
export type Modelid4 = string
export type Modelid5 = string
export type Success41 = boolean
export type Message40 = string
export type Error40 = string
export type Timestamp24 = string
export type Modelid6 = string
export type Model2 = string
export type Prompttokens = number
export type Completiontokens = number
export type Totaltokens = number
export type Cost = number
export type Requesttype = string
export type Dimension3 = string
export type Days1 = number
export type Startdate5 = (string | null)
export type Enddate5 = (string | null)
export type Modelconfigid = (string | null)
export type Success42 = boolean
export type Message41 = string
export type Error41 = string
export type Timestamp25 = string
export type Dimension4 = (string | null)
export type Days2 = (number | null)
export type Success43 = boolean
export type Message42 = string
export type Timestamp26 = string
export type Success44 = boolean
export type Path = string
export type Timestamp27 = string
export type Success45 = boolean
export type Message43 = string
export type Error42 = string
export type Language = string
export type Timestamp28 = string
export type Databasepath = (string | null)
export type Screenshotsavepath = (string | null)
export type Language1 = (string | null)
export type Success46 = boolean
export type Message44 = string
export type Timestamp29 = string
export type Success47 = boolean
export type Message45 = string
export type Error43 = string
export type Compressionlevel = number
export type Enableregioncropping = boolean
export type Cropthreshold = number
export type Timestamp30 = string
export type Compressionlevel1 = (string | null)
export type Enableregioncropping1 = (boolean | null)
export type Cropthreshold1 = (number | null)
export type Success48 = boolean
export type Message46 = string
export type Error44 = string
export type Timestamp31 = string
export type Success49 = boolean
export type Message47 = string
export type Error45 = string
export type Totalprocessed = number
export type Totalsavedbytes = number
export type Averagecompressionratio = number
export type Timestamp32 = string
export type Success50 = boolean
export type Message48 = string
export type Error46 = string
export type Hasmodels = boolean
export type Hasactivemodel = boolean
export type Hascompletedsetup = boolean
export type Needssetup = boolean
export type Modelcount = number
export type Timestamp33 = string
export type Success51 = boolean
export type Message49 = string
export type Error47 = string
export type Timestamp34 = string
export type Show = string
export type Hide = string
export type Dashboard = string
export type Activity = string
export type Chat = string
export type Agents = string
export type Settings1 = string
export type About = string
export type Quit = string
export type Success52 = boolean
export type Message50 = string
export type Error48 = string
export type Visible = boolean
export type Success53 = boolean
export type Message51 = string
export type Error49 = string
export type Visible1 = boolean
export type Name4 = string
export type RootModelStr = string

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
get_activities: {
input: GetActivitiesRequest
output: DataResponse
}
get_activity_by_id: {
input: GetActivityByIdRequest
output: DataResponse
}
get_activities_incremental: {
input: GetActivitiesIncrementalRequest
output: IncrementalActivitiesResponse
}
get_activity_count_by_date: {
input: GetActivityCountByDateRequest
output: ActivityCountResponse
}
get_events_by_activity: {
input: GetEventsByActivityRequest
output: GetEventsByActivityResponse
}
delete_activity: {
input: DeleteActivityRequest
output: TimedOperationResponse
}
delete_activities_by_date: {
input: DeleteActivitiesByDateRequest
output: TimedOperationResponse
}
merge_activities_handler: {
input: MergeActivitiesRequest
output: MergeActivitiesResponse
}
split_activity_handler: {
input: SplitActivityRequest
output: SplitActivityResponse
}
save_activity_rating: {
input: SaveActivityRatingRequest
output: SaveActivityRatingResponse
}
get_activity_ratings: {
input: GetActivityRatingsRequest
output: GetActivityRatingsResponse
}
delete_activity_rating: {
input: DeleteActivityRatingRequest
output: TimedOperationResponse
}
create_task: {
input: CreateTaskRequest
output: AgentResponse
}
execute_task: {
input: ExecuteTaskRequest
output: AgentResponse
}
delete_task: {
input: DeleteTaskRequest
output: AgentResponse
}
get_tasks: {
input: GetTasksRequest
output: AgentResponse
}
get_available_agents: {
input: GetAvailableAgentsRequest
output: AgentResponse
}
get_task_status: {
input: ExecuteTaskRequest
output: AgentResponse
}
schedule_task: {
input: ScheduleTaskRequest
output: AgentResponse
}
unschedule_task: {
input: UnscheduleTaskRequest
output: AgentResponse
}
get_tasks_by_date: {
input: GetTasksByDateRequest
output: AgentResponse
}
execute_task_in_chat: {
input: ExecuteTaskInChatRequest
output: AgentResponse
}
create_conversation: {
input: CreateConversationRequest
output: RootModelDictStrAny
}
create_conversation_from_activities: {
input: CreateConversationFromActivitiesRequest
output: RootModelDictStrAny
}
send_message: {
input: SendMessageRequest
output: RootModelDictStrAny
}
get_conversations: {
input: GetConversationsRequest
output: RootModelDictStrAny
}
get_messages: {
input: GetMessagesRequest
output: RootModelDictStrAny
}
delete_conversation: {
input: DeleteConversationRequest
output: RootModelDictStrAny
}
get_streaming_status: {
input: GetStreamingStatusRequest
output: RootModelDictStrAny
}
cancel_stream: {
input: CancelStreamRequest
output: RootModelDictStrAny
}
get_friendly_chat_settings: {
input: void | undefined
output: FriendlyChatResponse
}
update_friendly_chat_settings: {
input: UpdateFriendlyChatSettingsRequest
output: FriendlyChatResponse
}
get_friendly_chat_history: {
input: GetFriendlyChatHistoryRequest
output: FriendlyChatResponse
}
trigger_friendly_chat: {
input: void | undefined
output: FriendlyChatResponse
}
get_live2d_settings: {
input: void | undefined
output: RootModelDictStrAny
}
update_live2d_settings: {
input: UpdateLive2DSettingsRequest
output: RootModelDictStrAny
}
get_events: {
input: GetEventsRequest
output: DataResponse
}
get_event_by_id: {
input: GetEventByIdRequest
output: DataResponse
}
get_actions_by_event: {
input: GetActionsByEventRequest
output: GetActionsByEventResponse
}
delete_event: {
input: DeleteEventRequest
output: TimedOperationResponse
}
get_actions_by_activity: {
input: GetActionsByEventRequest
output: GetActionsByEventResponse
}
get_recent_events: {
input: GetRecentEventsRequest
output: RootModelDictStrAny
}
get_knowledge_list: {
input: void | undefined
output: RootModelDictStrAny
}
delete_knowledge: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
toggle_knowledge_favorite: {
input: ToggleKnowledgeFavoriteRequest
output: ToggleKnowledgeFavoriteResponse
}
create_knowledge: {
input: CreateKnowledgeRequest
output: CreateKnowledgeResponse
}
get_todo_list: {
input: GetTodoListRequest
output: RootModelDictStrAny
}
delete_todo: {
input: DeleteItemRequest
output: RootModelDictStrAny
}
schedule_todo: {
input: ScheduleTodoRequest
output: RootModelDictStrAny
}
unschedule_todo: {
input: UnscheduleTodoRequest
output: RootModelDictStrAny
}
generate_diary: {
input: GenerateDiaryRequest
output: GenerateDiaryResponse
}
get_diary_list: {
input: GetDiaryListRequest
output: GetDiaryListResponse
}
delete_diary: {
input: DeleteItemRequest
output: DeleteDiaryResponse
}
get_pipeline_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_event_count_by_date: {
input: void | undefined
output: RootModelDictStrAny
}
get_knowledge_count_by_date: {
input: void | undefined
output: RootModelDictStrAny
}
get_monitors: {
input: void | undefined
output: RootModelDictStrAny
}
start_monitors_auto_refresh: {
input: StartMonitorsAutoRefreshRequest
output: RootModelDictStrAny
}
stop_monitors_auto_refresh: {
input: void | undefined
output: RootModelDictStrAny
}
get_monitors_auto_refresh_status: {
input: void | undefined
output: RootModelDictStrAny
}
get_screen_settings: {
input: void | undefined
output: RootModelDictStrAny
}
capture_all_previews: {
input: void | undefined
output: RootModelDictStrAny
}
update_screen_settings: {
input: UpdateScreenSettingsRequest
output: RootModelDictStrAny
}
get_perception_settings: {
input: void | undefined
output: RootModelDictStrAny
}
update_perception_settings: {
input: UpdatePerceptionSettingsRequest
output: RootModelDictStrAny
}
get_perception_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_records: {
input: GetRecordsRequest
output: RootModelDictStrAny
}
start_perception: {
input: void | undefined
output: RootModelDictStrAny
}
stop_perception: {
input: void | undefined
output: RootModelDictStrAny
}
clear_records: {
input: void | undefined
output: RootModelDictStrAny
}
get_buffered_events: {
input: void | undefined
output: RootModelDictStrAny
}
check_permissions: {
input: void | undefined
output: PermissionsCheckResponse
}
open_system_settings: {
input: OpenSystemSettingsRequest
output: OpenSystemSettingsResponse
}
request_accessibility_permission: {
input: void | undefined
output: AccessibilityPermissionResponse
}
restart_app: {
input: RestartAppRequest
output: RestartAppResponse
}
start_pomodoro: {
input: StartPomodoroRequest
output: StartPomodoroResponse
}
end_pomodoro: {
input: EndPomodoroRequest
output: EndPomodoroResponse
}
get_pomodoro_status: {
input: void | undefined
output: GetPomodoroStatusResponse
}
retry_work_phase_aggregation: {
input: RetryWorkPhaseRequest
output: EndPomodoroResponse
}
find_unlinked_activities: {
input: FindUnlinkedActivitiesRequest
output: FindUnlinkedActivitiesResponse
}
link_activities_to_session: {
input: LinkActivitiesRequest
output: LinkActivitiesResponse
}
get_pomodoro_presets: {
input: void | undefined
output: GetPomodoroPresetsResponse
}
get_pomodoro_stats: {
input: GetPomodoroStatsRequest
output: GetPomodoroStatsResponse
}
get_pomodoro_session_detail: {
input: GetPomodoroSessionDetailRequest
output: GetPomodoroSessionDetailResponse
}
get_pomodoro_period_stats: {
input: GetPomodoroPeriodStatsRequest
output: GetPomodoroPeriodStatsResponse
}
delete_pomodoro_session: {
input: DeletePomodoroSessionRequest
output: DeletePomodoroSessionResponse
}
get_processing_stats: {
input: void | undefined
output: TimedOperationResponse
}
get_persistence_stats: {
input: void | undefined
output: DataResponse
}
start_processing: {
input: void | undefined
output: TimedOperationResponse
}
stop_processing: {
input: void | undefined
output: TimedOperationResponse
}
finalize_current_activity: {
input: void | undefined
output: TimedOperationResponse
}
cleanup_old_data: {
input: CleanupOldDataRequest
output: TimedOperationResponse
}
cleanup_orphaned_images: {
input: void | undefined
output: TimedOperationResponse
}
delete_knowledge_by_date: {
input: DeleteKnowledgeByDateRequest
output: TimedOperationResponse
}
delete_todos_by_date: {
input: DeleteTodosByDateRequest
output: TimedOperationResponse
}
delete_diaries_by_date: {
input: DeleteDiariesByDateRequest
output: TimedOperationResponse
}
get_image_stats: {
input: void | undefined
output: ImageStatsResponse
}
get_cached_images: {
input: GetImagesRequest
output: CachedImagesResponse
}
cleanup_old_images: {
input: CleanupImagesRequest
output: CleanupImagesResponse
}
clear_memory_cache: {
input: void | undefined
output: ClearMemoryCacheResponse
}
get_image_optimization_config: {
input: void | undefined
output: GetImageOptimizationConfigResponse
}
get_image_optimization_stats: {
input: void | undefined
output: ImageOptimizationStatsResponse
}
update_image_optimization_config: {
input: ImageOptimizationConfigRequest
output: UpdateImageOptimizationConfigResponseV2
}
read_image_file: {
input: ReadImageFileRequest
output: ReadImageFileResponse
}
check_image_persistence_health: {
input: void | undefined
output: ImagePersistenceHealthResponse
}
cleanup_broken_action_images: {
input: CleanupBrokenActionsRequest
output: CleanupBrokenActionsResponse
}
create_model: {
input: CreateModelRequest
output: ModelOperationResponse
}
update_model: {
input: UpdateModelRequest
output: ModelOperationResponse
}
delete_model: {
input: DeleteModelRequest
output: ModelOperationResponse
}
list_models: {
input: void | undefined
output: ModelOperationResponse
}
get_active_model: {
input: void | undefined
output: ModelOperationResponse
}
select_model: {
input: SelectModelRequest
output: ModelOperationResponse
}
test_model: {
input: TestModelRequest
output: ModelOperationResponse
}
migrate_models_to_openai: {
input: void | undefined
output: ModelOperationResponse
}
get_llm_stats: {
input: void | undefined
output: DashboardResponse
}
get_llm_stats_by_model: {
input: GetLLMStatsByModelRequest
output: DashboardResponse
}
record_llm_usage: {
input: RecordLLMUsageRequest
output: DashboardResponse
}
get_usage_summary: {
input: void | undefined
output: DashboardResponse
}
get_daily_llm_usage: {
input: void | undefined
output: DashboardResponse
}
get_model_distribution: {
input: void | undefined
output: DashboardResponse
}
get_llm_usage_trend: {
input: GetLLMUsageTrendRequest
output: LLMUsageTrendResponse
}
start_system: {
input: void | undefined
output: SystemResponse
}
stop_system: {
input: void | undefined
output: SystemResponse
}
get_system_stats: {
input: void | undefined
output: SystemResponse
}
get_database_path: {
input: void | undefined
output: DatabasePathResponse
}
get_settings_info: {
input: void | undefined
output: GetSettingsInfoResponse
}
update_settings: {
input: UpdateSettingsRequest
output: UpdateSettingsResponse
}
get_image_compression_config: {
input: void | undefined
output: GetImageCompressionConfigResponse
}
update_image_compression_config: {
input: ImageCompressionConfigRequest
output: UpdateImageCompressionConfigResponseV2
}
get_image_compression_stats: {
input: void | undefined
output: GetImageCompressionStatsResponse
}
reset_image_compression_stats: {
input: void | undefined
output: TimedOperationResponse
}
check_initial_setup: {
input: void | undefined
output: CheckInitialSetupResponse
}
complete_initial_setup: {
input: void | undefined
output: CompleteInitialSetupResponse
}
update_tray_menu: {
input: TrayUpdateRequest
output: TrayUpdateResponse
}
set_tray_visibility: {
input: TrayVisibilityRequest
output: TrayVisibilityResponse
}
greeting: {
input: Person
output: RootModelStr
}
}
/**
 * Request parameters for getting activities.
 * 
 * @property limit - Maximum number of activities to return (1-100).
 * @property offset - Number of activities to skip (>=0).
 * @property start - Optional start date filter (YYYY-MM-DD format).
 * @property end - Optional end date filter (YYYY-MM-DD format).
 */
export interface GetActivitiesRequest {
limit?: Limit
offset?: Offset
start?: Start
end?: End
}
/**
 * Generic response with data field and timestamp
 */
export interface DataResponse {
success: Success
message?: Message
error?: Error
data?: unknown
timestamp?: Timestamp
}
/**
 * Request parameters for getting activity by ID.
 * 
 * @property activityId - The activity ID.
 */
export interface GetActivityByIdRequest {
activityId: Activityid
}
/**
 * Request parameters for incremental activity updates.
 * 
 * @property version - The current version number from client (starts at 0).
 * @property limit - Maximum number of new activities to return (1-100).
 */
export interface GetActivitiesIncrementalRequest {
version?: Version
limit?: Limit1
}
/**
 * Incremental activities response
 */
export interface IncrementalActivitiesResponse {
success: Success1
data: IncrementalActivitiesData
}
/**
 * Incremental activities data
 */
export interface IncrementalActivitiesData {
activities: Activities
count: Count
maxVersion: Maxversion
}
/**
 * Request parameters for getting activity count by date.
 * 
 * Returns the total activity count for each date (no pagination, gets total count for all dates).
 */
export interface GetActivityCountByDateRequest {

}
/**
 * Activity count by date response
 */
export interface ActivityCountResponse {
success: Success2
data: ActivityCountData
error?: Error1
}
/**
 * Activity count data
 */
export interface ActivityCountData {
dateCountMap: Datecountmap
totalDates: Totaldates
totalActivities: Totalactivities
}
export interface Datecountmap {
[k: string]: number
}
/**
 * Request parameters for getting events by activity ID.
 * 
 * @property activityId - The activity ID to get events for.
 */
export interface GetEventsByActivityRequest {
activityId: Activityid1
}
/**
 * Response containing events for a specific activity
 */
export interface GetEventsByActivityResponse {
success: Success3
message?: Message1
error?: Error2
events: Events
}
/**
 * Event response data for three-layer architecture
 */
export interface EventResponse {
id: Id
title: Title
description: Description
startTime: Starttime
endTime: Endtime
sourceActionIds: Sourceactionids
createdAt: Createdat
}
/**
 * Request parameters for deleting an activity.
 * 
 * @property activityId - The activity ID to delete.
 */
export interface DeleteActivityRequest {
activityId: Activityid2
}
/**
 * Operation response with timestamp.
 */
export interface TimedOperationResponse {
success: Success4
message?: Message2
error?: Error3
data?: unknown
timestamp?: Timestamp1
}
/**
 * Request parameters for deleting activities in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteActivitiesByDateRequest {
startDate: Startdate
endDate: Enddate
}
/**
 * Request parameters for merging multiple activities into one.
 * 
 * @property activityIds - List of activity IDs to merge.
 * @property mergedTitle - Optional title for the merged activity.
 * @property mergedDescription - Optional description for the merged activity.
 */
export interface MergeActivitiesRequest {
activityIds: Activityids
mergedTitle?: Mergedtitle
mergedDescription?: Mergeddescription
}
/**
 * Response after merging multiple activities
 */
export interface MergeActivitiesResponse {
success: Success5
message?: Message3
error?: Error4
mergedActivityId?: Mergedactivityid
}
/**
 * Request parameters for splitting an activity into multiple activities.
 * 
 * @property activityId - The activity ID to split.
 * @property splitPoints - List of split points defining new activities.
 */
export interface SplitActivityRequest {
activityId: Activityid3
splitPoints: Splitpoints
}
/**
 * A split point defining a new activity when splitting.
 * 
 * @property title - Title for the new activity.
 * @property description - Description for the new activity.
 * @property eventIndexes - List of event indexes (1-based) to include in this split.
 */
export interface SplitPoint {
title: Title1
description: Description1
eventIndexes: Eventindexes
}
/**
 * Response after splitting an activity into multiple activities
 */
export interface SplitActivityResponse {
success: Success6
message?: Message4
error?: Error5
newActivityIds?: Newactivityids
}
/**
 * Request to save or update an activity rating
 */
export interface SaveActivityRatingRequest {
activityId: Activityid4
dimension: Dimension
rating: Rating
note?: Note
}
/**
 * Response after saving a rating
 */
export interface SaveActivityRatingResponse {
success: Success7
message?: Message5
error?: Error6
data?: (ActivityRatingData | null)
timestamp?: Timestamp2
}
/**
 * Individual rating record
 */
export interface ActivityRatingData {
id: Id1
activityId: Activityid5
dimension: Dimension1
rating: Rating1
note?: Note1
createdAt: Createdat1
updatedAt: Updatedat
}
/**
 * Request to get ratings for an activity
 */
export interface GetActivityRatingsRequest {
activityId: Activityid6
}
/**
 * Response with list of ratings
 */
export interface GetActivityRatingsResponse {
success: Success8
message?: Message6
error?: Error7
data?: Data2
timestamp?: Timestamp3
}
/**
 * Request to delete a specific rating
 */
export interface DeleteActivityRatingRequest {
activityId: Activityid7
dimension: Dimension2
}
/**
 * Request parameters for creating a new agent task.
 * 
 * @property agent - The agent type to use.
 * @property planDescription - The task description/plan.
 */
export interface CreateTaskRequest {
agent: Agent
planDescription: Plandescription
}
/**
 * Standard agent handler response.
 */
export interface AgentResponse {
success: Success9
message?: Message7
error?: Error8
data?: Data3
}
/**
 * Request parameters for executing a task.
 * 
 * @property taskId - The task ID to execute.
 */
export interface ExecuteTaskRequest {
taskId: Taskid
}
/**
 * Request parameters for deleting a task.
 * 
 * @property taskId - The task ID to delete.
 */
export interface DeleteTaskRequest {
taskId: Taskid1
}
/**
 * Request parameters for getting tasks.
 * 
 * @property limit - Maximum number of tasks to return (1-100).
 * @property status - Optional status filter.
 */
export interface GetTasksRequest {
limit?: Limit2
status?: Status
}
/**
 * Request parameters for getting available agents.
 * 
 * No parameters needed.
 */
export interface GetAvailableAgentsRequest {

}
/**
 * Request parameters for scheduling a task to a specific date.
 * 
 * @property taskId - The task ID to schedule.
 * @property scheduledDate - The date to schedule the task (YYYY-MM-DD format).
 */
export interface ScheduleTaskRequest {
taskId: Taskid2
scheduledDate: Scheduleddate
}
/**
 * Request parameters for moving a task back to pending.
 * 
 * @property taskId - The task ID to unschedule.
 */
export interface UnscheduleTaskRequest {
taskId: Taskid3
}
/**
 * Request parameters for getting tasks scheduled for a specific date.
 * 
 * @property scheduledDate - The date to query tasks (YYYY-MM-DD format).
 */
export interface GetTasksByDateRequest {
scheduledDate: Scheduleddate1
}
/**
 * Request parameters for executing a task in chat.
 * 
 * @property taskId - The task ID to execute.
 * @property conversationId - Optional conversation ID, creates new if not provided.
 */
export interface ExecuteTaskInChatRequest {
taskId: Taskid4
conversationId?: Conversationid
}
/**
 * Request parameters for creating a new conversation.
 * 
 * @property title - Conversation title.
 * @property relatedActivityIds - Optional list of related activity IDs.
 * @property metadata - Optional metadata dictionary.
 * @property modelId - Optional model ID for this conversation.
 */
export interface CreateConversationRequest {
title: Title2
relatedActivityIds?: Relatedactivityids
metadata?: Metadata
modelId?: Modelid
}
export interface RootModelDictStrAny {
[k: string]: unknown
}
/**
 * Request parameters for creating a conversation from activities.
 * 
 * @property activityIds - List of activity IDs to create conversation from.
 */
export interface CreateConversationFromActivitiesRequest {
activityIds: Activityids1
}
/**
 * Request parameters for sending a message in a conversation.
 * 
 * @property conversationId - The conversation ID.
 * @property content - Message content.
 * @property images - Optional list of base64 encoded images or file paths.
 * @property modelId - Optional LLM model ID to use for this message.
 */
export interface SendMessageRequest {
conversationId: Conversationid1
content: Content
images?: Images
modelId?: Modelid1
}
/**
 * Request parameters for getting conversation list.
 * 
 * @property limit - Maximum number of conversations to return (1-100).
 * @property offset - Number of conversations to skip (>=0).
 */
export interface GetConversationsRequest {
limit?: Limit3
offset?: Offset1
}
/**
 * Request parameters for getting messages in a conversation.
 * 
 * @property conversationId - The conversation ID.
 * @property limit - Maximum number of messages to return (1-100).
 * @property offset - Number of messages to skip (>=0).
 */
export interface GetMessagesRequest {
conversationId: Conversationid2
limit?: Limit4
offset?: Offset2
}
/**
 * Request parameters for deleting a conversation.
 * 
 * @property conversationId - The conversation ID to delete.
 */
export interface DeleteConversationRequest {
conversationId: Conversationid3
}
/**
 * Request parameters for getting streaming status.
 * 
 * @property conversationIds - Optional list of conversation IDs to check. If None, returns all active streams.
 */
export interface GetStreamingStatusRequest {
conversationIds?: Conversationids
}
/**
 * Request parameters for cancelling a streaming output.
 * 
 * @property conversationId - The conversation ID to cancel streaming for.
 */
export interface CancelStreamRequest {
conversationId: Conversationid4
}
/**
 * Response model for friendly chat handlers.
 */
export interface FriendlyChatResponse {
success: Success10
message?: Message8
error?: Error9
data?: Data4
}
/**
 * Request parameters for updating friendly chat settings.
 * 
 * @property enabled - Whether friendly chat feature is enabled.
 * @property interval - Interval in minutes for generating chat messages (1-120).
 * @property dataWindow - Time window in minutes for analyzing recent activities (5-120).
 * @property enableSystemNotification - Whether to show system notifications.
 * @property enableLive2dDisplay - Whether to display in Live2D character.
 */
export interface UpdateFriendlyChatSettingsRequest {
enabled?: Enabled
interval?: Interval
dataWindow?: Datawindow
enableSystemNotification?: Enablesystemnotification
enableLive2DDisplay?: Enablelive2Ddisplay
}
/**
 * Request parameters for getting friendly chat history.
 * 
 * @property limit - Maximum number of chat messages to return (1-100).
 * @property offset - Number of messages to skip (>=0).
 */
export interface GetFriendlyChatHistoryRequest {
limit?: Limit5
offset?: Offset3
}
/**
 * Request parameters for updating Live2D configuration.
 * 
 * @property enabled - Whether the Live2D companion window should be shown.
 * @property selectedModelUrl - Currently selected Live2D model URL.
 * @property modelDir - Optional local model directory path.
 * @property remoteModels - Remote model URLs saved in configuration.
 * @property notificationDuration - Duration in milliseconds for notification display (1000-30000).
 */
export interface UpdateLive2DSettingsRequest {
enabled?: Enabled1
selectedModelUrl?: Selectedmodelurl
modelDir?: Modeldir
remoteModels?: Remotemodels
notificationDuration?: Notificationduration
}
/**
 * Request parameters for getting events.
 * 
 * @property limit - Maximum number of events to return (1-500).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetEventsRequest {
limit?: Limit6
eventType?: Eventtype
startTime?: Starttime1
endTime?: Endtime1
}
/**
 * Request parameters for getting event by ID.
 * 
 * @property eventId - The event ID.
 */
export interface GetEventByIdRequest {
eventId: Eventid
}
/**
 * Request parameters for getting actions by event ID.
 * 
 * @property eventId - The event ID to get actions for.
 */
export interface GetActionsByEventRequest {
eventId: Eventid1
}
/**
 * Response containing actions for a specific event
 */
export interface GetActionsByEventResponse {
success: Success11
message?: Message9
error?: Error10
actions: Actions
}
/**
 * Action response data for three-layer architecture
 */
export interface ActionResponse {
id: Id2
title: Title3
description: Description2
keywords: Keywords
timestamp: Timestamp4
screenshots: Screenshots
createdAt: Createdat2
}
/**
 * Request parameters for deleting an event.
 * 
 * @property eventId - The event ID to delete.
 */
export interface DeleteEventRequest {
eventId: Eventid2
}
/**
 * Request parameters for getting recent events.
 * 
 * @property limit - Maximum number of events to return (1-200).
 * @property offset - Number of events to skip (>=0).
 */
export interface GetRecentEventsRequest {
limit?: Limit7
offset?: Offset4
}
/**
 * Request parameters for deleting an item (knowledge/todo/diary).
 * 
 * @property id - The item ID to delete.
 */
export interface DeleteItemRequest {
id: Id3
}
/**
 * Request parameters for toggling knowledge favorite status.
 * 
 * @property id - Knowledge ID to toggle favorite status
 */
export interface ToggleKnowledgeFavoriteRequest {
id: Id4
}
/**
 * Response after toggling knowledge favorite status
 */
export interface ToggleKnowledgeFavoriteResponse {
success: Success12
message?: Message10
error?: Error11
data?: (KnowledgeData | null)
timestamp?: Timestamp5
}
/**
 * Knowledge item data
 */
export interface KnowledgeData {
id: Id5
title: Title4
description: Description3
keywords: Keywords1
createdAt?: Createdat3
sourceActionId?: Sourceactionid
favorite?: Favorite
deleted?: Deleted
}
/**
 * Request parameters for manually creating knowledge.
 * 
 * @property title - Knowledge title
 * @property description - Knowledge description
 * @property keywords - List of keywords/tags
 */
export interface CreateKnowledgeRequest {
title: Title5
description: Description4
keywords?: Keywords2
}
/**
 * Response after creating knowledge
 */
export interface CreateKnowledgeResponse {
success: Success13
message?: Message11
error?: Error12
data?: (KnowledgeData | null)
timestamp?: Timestamp6
}
/**
 * Request parameters for getting todo list.
 * 
 * @property includeCompleted - Whether to include completed todos.
 */
export interface GetTodoListRequest {
includeCompleted?: Includecompleted
}
/**
 * Request parameters for scheduling a todo to a specific date.
 * 
 * @property todoId - The todo ID to schedule.
 * @property scheduledDate - The date to schedule the todo (YYYY-MM-DD format).
 * @property scheduledTime - Optional time to schedule the todo (HH:MM format).
 * @property scheduledEndTime - Optional end time for the todo (HH:MM format).
 * @property recurrenceRule - Optional recurrence configuration (dict with type and interval).
 */
export interface ScheduleTodoRequest {
todoId: Todoid
scheduledDate: Scheduleddate2
scheduledTime?: Scheduledtime
scheduledEndTime?: Scheduledendtime
recurrenceRule?: Recurrencerule
}
/**
 * Request parameters for unscheduling a todo.
 * 
 * @property todoId - The todo ID to unschedule.
 */
export interface UnscheduleTodoRequest {
todoId: Todoid1
}
/**
 * Request parameters for generating a diary.
 * 
 * @property date - The date for the diary (YYYY-MM-DD format).
 */
export interface GenerateDiaryRequest {
date: Date
}
/**
 * Response after generating a diary
 */
export interface GenerateDiaryResponse {
success: Success14
message?: Message12
error?: Error13
data?: (DiaryData | null)
timestamp?: Timestamp7
}
/**
 * Diary data
 */
export interface DiaryData {
id: Id6
date: Date1
content: Content1
sourceActivityIds: Sourceactivityids
createdAt: Createdat4
}
/**
 * Request parameters for getting diary list.
 * 
 * @property limit - Maximum number of diaries to return (1-100).
 */
export interface GetDiaryListRequest {
limit?: Limit8
}
/**
 * Response containing diary list
 */
export interface GetDiaryListResponse {
success: Success15
message?: Message13
error?: Error14
data?: (DiaryListData | null)
timestamp?: Timestamp8
}
/**
 * Diary list data
 */
export interface DiaryListData {
diaries: Diaries
count: Count1
}
/**
 * Response after deleting a diary
 */
export interface DeleteDiaryResponse {
success: Success16
message?: Message14
error?: Error15
timestamp?: Timestamp9
}
/**
 * Request to start monitors auto refresh.
 */
export interface StartMonitorsAutoRefreshRequest {
intervalSeconds?: Intervalseconds
}
/**
 * Request to update screen capture settings.
 */
export interface UpdateScreenSettingsRequest {
screens: Screens
}
/**
 * Single screen setting.
 */
export interface ScreenSetting {
monitorIndex: Monitorindex
monitorName?: Monitorname
isEnabled?: Isenabled
resolution?: Resolution
isPrimary?: Isprimary
}
/**
 * Request to update perception settings.
 */
export interface UpdatePerceptionSettingsRequest {
keyboardEnabled?: Keyboardenabled
mouseEnabled?: Mouseenabled
}
/**
 * Request parameters for getting records.
 * 
 * @property limit - Maximum number of records to return (1-1000).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetRecordsRequest {
limit?: Limit9
eventType?: Eventtype1
startTime?: Starttime2
endTime?: Endtime2
}
/**
 * Permission check response
 */
export interface PermissionsCheckResponse {
allGranted: Allgranted
permissions: Permissions
platform: Platform
needsRestart: Needsrestart
}
export interface Permissions {
[k: string]: PermissionInfo
}
/**
 * Single permission information
 */
export interface PermissionInfo {
type: PermissionType
status: PermissionStatus
name: Name
description: Description5
required: Required
systemSettingsPath: Systemsettingspath
}
/**
 * Open system settings request
 */
export interface OpenSystemSettingsRequest {
permissionType: PermissionType
}
/**
 * Response for opening system settings
 */
export interface OpenSystemSettingsResponse {
success: Success17
message?: Message15
error?: Error16
}
/**
 * Response for requesting accessibility permission
 */
export interface AccessibilityPermissionResponse {
success: Success18
message?: Message16
error?: Error17
granted?: Granted
}
/**
 * Restart app request
 */
export interface RestartAppRequest {
delaySeconds?: Delayseconds
}
/**
 * Response for restarting the application
 */
export interface RestartAppResponse {
success: Success19
message?: Message17
error?: Error18
delaySeconds?: Delayseconds1
timestamp?: Timestamp10
}
/**
 * Start Pomodoro request with rounds configuration
 */
export interface StartPomodoroRequest {
userIntent: Userintent
durationMinutes?: Durationminutes
associatedTodoId?: Associatedtodoid
workDurationMinutes?: Workdurationminutes
breakDurationMinutes?: Breakdurationminutes
totalRounds?: Totalrounds
}
/**
 * Response after starting a Pomodoro session
 */
export interface StartPomodoroResponse {
success: Success20
message?: Message18
error?: Error19
data?: (PomodoroSessionData | null)
timestamp?: Timestamp11
}
/**
 * Pomodoro session data with rounds support
 */
export interface PomodoroSessionData {
sessionId: Sessionid
userIntent: Userintent1
startTime: Starttime3
elapsedMinutes: Elapsedminutes
plannedDurationMinutes: Planneddurationminutes
associatedTodoId?: Associatedtodoid1
associatedTodoTitle?: Associatedtodotitle
workDurationMinutes?: Workdurationminutes1
breakDurationMinutes?: Breakdurationminutes1
totalRounds?: Totalrounds1
currentRound?: Currentround
currentPhase?: Currentphase
phaseStartTime?: Phasestarttime
completedRounds?: Completedrounds
remainingPhaseSeconds?: Remainingphaseseconds
pureWorkDurationMinutes?: Pureworkdurationminutes
}
/**
 * End Pomodoro request
 */
export interface EndPomodoroRequest {
status?: Status1
}
/**
 * Response after ending a Pomodoro session
 */
export interface EndPomodoroResponse {
success: Success21
message?: Message19
error?: Error20
data?: (EndPomodoroData | null)
timestamp?: Timestamp12
}
/**
 * End Pomodoro session result data
 */
export interface EndPomodoroData {
sessionId: Sessionid1
processingJobId?: Processingjobid
rawRecordsCount?: Rawrecordscount
message?: Message20
}
/**
 * Response for getting current Pomodoro session status
 */
export interface GetPomodoroStatusResponse {
success: Success22
message?: Message21
error?: Error21
data?: (PomodoroSessionData | null)
timestamp?: Timestamp13
}
/**
 * Retry work phase activity aggregation request
 */
export interface RetryWorkPhaseRequest {
sessionId: Sessionid2
workPhase: Workphase
}
/**
 * Request to find activities that could be linked to a session
 */
export interface FindUnlinkedActivitiesRequest {
sessionId: Sessionid3
}
/**
 * Response with unlinked activities
 */
export interface FindUnlinkedActivitiesResponse {
success: Success23
message?: Message22
error?: Error22
data?: unknown
timestamp?: Timestamp14
activities?: Activities1
}
/**
 * Activity that could be linked to session
 */
export interface UnlinkedActivityData {
id: Id7
title: Title6
startTime: Starttime4
endTime: Endtime3
sessionDurationMinutes: Sessiondurationminutes
}
/**
 * Request to link activities to a session
 */
export interface LinkActivitiesRequest {
sessionId: Sessionid4
activityIds: Activityids2
}
/**
 * Response after linking activities
 */
export interface LinkActivitiesResponse {
success: Success24
message?: Message23
error?: Error23
data?: unknown
timestamp?: Timestamp15
linkedCount?: Linkedcount
}
/**
 * Response with list of Pomodoro presets
 */
export interface GetPomodoroPresetsResponse {
success: Success25
message?: Message24
error?: Error24
data?: Data7
timestamp?: Timestamp16
}
/**
 * Pomodoro configuration preset
 */
export interface PomodoroPreset {
id: Id8
name: Name1
description: Description6
workDurationMinutes: Workdurationminutes2
breakDurationMinutes: Breakdurationminutes2
totalRounds: Totalrounds2
icon?: Icon
}
/**
 * Request to get Pomodoro statistics for a specific date
 */
export interface GetPomodoroStatsRequest {
date: Date2
}
/**
 * Response with Pomodoro statistics
 */
export interface GetPomodoroStatsResponse {
success: Success26
message?: Message25
error?: Error25
data?: (PomodoroStatsData | null)
timestamp?: Timestamp17
}
/**
 * Pomodoro statistics for a specific date
 */
export interface PomodoroStatsData {
date: Date3
completedCount: Completedcount
totalFocusMinutes: Totalfocusminutes
averageDurationMinutes: Averagedurationminutes
sessions: Sessions
}
/**
 * Request to get detailed Pomodoro session information
 */
export interface GetPomodoroSessionDetailRequest {
sessionId: Sessionid5
}
/**
 * Response with detailed Pomodoro session data
 */
export interface GetPomodoroSessionDetailResponse {
success: Success27
message?: Message26
error?: Error26
data?: (PomodoroSessionDetailData | null)
timestamp?: Timestamp18
}
/**
 * Detailed Pomodoro session with activities and focus metrics
 */
export interface PomodoroSessionDetailData {
session: Session
activities: Activities2
focusMetrics: FocusMetrics
llmFocusEvaluation?: (LLMFocusEvaluation | null)
phaseTimeline?: Phasetimeline
}
export interface Session {
[k: string]: unknown
}
/**
 * Activity data for Pomodoro session detail view
 */
export interface PomodoroActivityData {
id: Id9
title: Title7
description: Description7
startTime: Starttime5
endTime: Endtime4
sessionDurationMinutes: Sessiondurationminutes1
workPhase?: Workphase1
focusScore?: Focusscore
topicTags?: Topictags
sourceEventIds?: Sourceeventids
sourceActionIds?: Sourceactionids1
aggregationMode?: Aggregationmode
}
/**
 * Focus metrics for a Pomodoro session
 */
export interface FocusMetrics {
overallFocusScore: Overallfocusscore
activityCount: Activitycount
topicDiversity: Topicdiversity
averageActivityDuration: Averageactivityduration
focusLevel: Focuslevel
}
/**
 * Complete LLM-based focus evaluation result
 */
export interface LLMFocusEvaluation {
focusScore: Focusscore1
focusLevel: Focuslevel1
dimensionScores: LLMFocusDimensionScores
analysis: LLMFocusAnalysis
workType: Worktype
isFocusedWork: Isfocusedwork
distractionPercentage: Distractionpercentage
deepWorkMinutes: Deepworkminutes
contextSummary: Contextsummary
}
/**
 * Detailed dimension scores from LLM evaluation
 */
export interface LLMFocusDimensionScores {
topicConsistency: Topicconsistency
durationDepth: Durationdepth
switchingRhythm: Switchingrhythm
workQuality: Workquality
goalOrientation: Goalorientation
}
/**
 * Detailed focus analysis from LLM evaluation
 */
export interface LLMFocusAnalysis {
strengths: Strengths
weaknesses: Weaknesses
suggestions: Suggestions
}
/**
 * Single phase in timeline (work or break)
 */
export interface PhaseTimelineItem {
phaseType: Phasetype
phaseNumber: Phasenumber
startTime: Starttime6
endTime: Endtime5
durationMinutes: Durationminutes1
}
/**
 * Request to get Pomodoro statistics for a time period
 */
export interface GetPomodoroPeriodStatsRequest {
period: Period
referenceDate?: Referencedate
}
/**
 * Response with Pomodoro period statistics
 */
export interface GetPomodoroPeriodStatsResponse {
success: Success28
message?: Message27
error?: Error27
data?: (PomodoroPeriodStatsData | null)
timestamp?: Timestamp19
}
/**
 * Pomodoro statistics for a time period
 */
export interface PomodoroPeriodStatsData {
period: Period1
startDate: Startdate1
endDate: Enddate1
weeklyTotal: Weeklytotal
focusHours: Focushours
dailyAverage: Dailyaverage
completionRate: Completionrate
dailyData: Dailydata
}
/**
 * Daily focus data for a specific day
 */
export interface DailyFocusData {
day: Day
date: Date4
sessions: Sessions1
minutes: Minutes
}
/**
 * Request to delete a Pomodoro session
 */
export interface DeletePomodoroSessionRequest {
sessionId: Sessionid6
}
/**
 * Response after deleting a Pomodoro session
 */
export interface DeletePomodoroSessionResponse {
success: Success29
message?: Message28
error?: Error28
data?: (DeletePomodoroSessionData | null)
timestamp?: Timestamp20
}
/**
 * Data returned after deleting a session
 */
export interface DeletePomodoroSessionData {
sessionId: Sessionid7
deletedActivitiesCount: Deletedactivitiescount
}
/**
 * Request parameters for cleaning up old data.
 * 
 * @property days - Number of days to keep (1-365).
 */
export interface CleanupOldDataRequest {
days?: Days
}
/**
 * Request parameters for deleting knowledge in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteKnowledgeByDateRequest {
startDate: Startdate2
endDate: Enddate2
}
/**
 * Request parameters for deleting todos in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteTodosByDateRequest {
startDate: Startdate3
endDate: Enddate3
}
/**
 * Request parameters for deleting diaries in a date range.
 * 
 * @property startDate - Start date in YYYY-MM-DD format.
 * @property endDate - End date in YYYY-MM-DD format.
 */
export interface DeleteDiariesByDateRequest {
startDate: Startdate4
endDate: Enddate4
}
/**
 * Response containing image cache statistics
 */
export interface ImageStatsResponse {
success: Success30
message?: Message29
error?: Error29
stats?: Stats
}
/**
 * Request parameters for batch getting images from cache.
 * 
 * @property hashes - List of image hashes to retrieve.
 */
export interface GetImagesRequest {
hashes: Hashes
}
/**
 * Response containing cached images in base64 format
 */
export interface CachedImagesResponse {
success: Success31
message?: Message30
error?: Error30
images: Images1
foundCount: Foundcount
requestedCount: Requestedcount
}
export interface Images1 {
[k: string]: string
}
/**
 * Request parameters for cleaning up old images.
 * 
 * @property maxAgeHours - Maximum age in hours for images to keep (images older than this will be deleted).
 */
export interface CleanupImagesRequest {
maxAgeHours?: Maxagehours
}
/**
 * Response after cleaning up old images
 */
export interface CleanupImagesResponse {
success: Success32
message?: Message31
error?: Error31
cleanedCount?: Cleanedcount
}
/**
 * Response after clearing memory cache
 */
export interface ClearMemoryCacheResponse {
success: Success33
message?: Message32
error?: Error32
clearedCount?: Clearedcount
}
/**
 * Response for get_image_optimization_config handler
 */
export interface GetImageOptimizationConfigResponse {
success: Success34
message?: Message33
error?: Error33
data?: (ImageOptimizationConfigData | null)
timestamp?: Timestamp21
}
/**
 * Image optimization configuration data
 */
export interface ImageOptimizationConfigData {
enabled?: Enabled2
strategy?: Strategy
phashThreshold?: Phashthreshold
minInterval?: Mininterval
enableContentAnalysis?: Enablecontentanalysis
enableTextDetection?: Enabletextdetection
}
/**
 * Response containing image optimization statistics
 */
export interface ImageOptimizationStatsResponse {
success: Success35
message?: Message34
error?: Error34
stats?: Stats1
config?: Config
}
/**
 * Request parameters for updating image optimization configuration.
 * 
 * @property enabled - Whether image optimization is enabled.
 * @property strategy - Optimization strategy ('phash', 'sampling', 'hybrid').
 * @property phashThreshold - Perceptual hash similarity threshold (0.0-1.0).
 * @property minInterval - Minimum time interval between images (seconds).
 * @property maxImages - Maximum number of images per event.
 * @property enableContentAnalysis - Enable content-based importance analysis.
 * @property enableTextDetection - Enable text detection for OCR-capable images.
 */
export interface ImageOptimizationConfigRequest {
enabled?: Enabled3
strategy?: Strategy1
phashThreshold?: Phashthreshold1
minInterval?: Mininterval1
maxImages?: Maximages
enableContentAnalysis?: Enablecontentanalysis1
enableTextDetection?: Enabletextdetection1
}
/**
 * Response for update_image_optimization_config handler
 */
export interface UpdateImageOptimizationConfigResponseV2 {
success: Success36
message?: Message35
error?: Error35
data?: (ImageOptimizationConfigData | null)
timestamp?: Timestamp22
}
/**
 * Request parameters for reading an image file.
 * 
 * @property filePath - Path to the image file to read.
 */
export interface ReadImageFileRequest {
filePath: Filepath
}
/**
 * Response containing image file data as base64
 */
export interface ReadImageFileResponse {
success: Success37
message?: Message36
error?: Error36
dataUrl?: Dataurl
}
/**
 * Response containing image persistence health check results
 */
export interface ImagePersistenceHealthResponse {
success: Success38
message?: Message37
error?: Error37
data?: (ImagePersistenceHealthData | null)
}
/**
 * Data model for image persistence health check
 */
export interface ImagePersistenceHealthData {
totalActions: Totalactions
actionsWithScreenshots: Actionswithscreenshots
actionsAllImagesOk: Actionsallimagesok
actionsPartialMissing: Actionspartialmissing
actionsAllMissing: Actionsallmissing
totalImageReferences: Totalimagereferences
imagesFound: Imagesfound
imagesMissing: Imagesmissing
missingRatePercent: Missingratepercent
memoryCacheCurrentSize: Memorycachecurrentsize
memoryCacheMaxSize: Memorycachemaxsize
memoryTtlSeconds: Memoryttlseconds
actionsWithIssues: Actionswithissues
}
/**
 * Request parameters for cleaning up actions with missing images.
 * 
 * @property strategy - Cleanup strategy: delete_actions, remove_references, or dry_run.
 * @property actionIds - Optional list of specific action IDs to process.
 */
export interface CleanupBrokenActionsRequest {
strategy: Strategy2
actionIds?: Actionids
}
/**
 * Response after cleaning up broken action images
 */
export interface CleanupBrokenActionsResponse {
success: Success39
message?: Message38
error?: Error38
actionsProcessed?: Actionsprocessed
actionsDeleted?: Actionsdeleted
referencesRemoved?: Referencesremoved
imagesRemoved?: Imagesremoved
}
/**
 * Request parameters for creating a new model configuration.
 * 
 * @property name - Display name for the model.
 * @property apiUrl - API endpoint base URL.
 * @property model - Model identifier/name.
 * @property inputTokenPrice - Price per million input tokens.
 * @property outputTokenPrice - Price per million output tokens.
 * @property currency - Currency code (optional, defaults to 'USD').
 * @property apiKey - API authentication key.
 * 
 * Note: Provider is automatically set to 'openai' for OpenAI-compatible APIs.
 */
export interface CreateModelRequest {
name: Name2
provider?: Provider
apiUrl: Apiurl
model: Model
inputTokenPrice: Inputtokenprice
outputTokenPrice: Outputtokenprice
currency?: Currency
apiKey: Apikey
}
/**
 * Generic model management response with optional payload and timestamp.
 */
export interface ModelOperationResponse {
success: Success40
message?: Message39
error?: Error39
data?: Data8
timestamp?: Timestamp23
}
/**
 * Request parameters for updating a model configuration.
 * 
 * @property modelId - The ID of the model to update.
 * @property name - Display name for the model (optional).
 * @property apiUrl - API endpoint base URL (optional).
 * @property model - Model identifier/name (optional).
 * @property inputTokenPrice - Price per million input tokens (optional).
 * @property outputTokenPrice - Price per million output tokens (optional).
 * @property currency - Currency code (optional).
 * @property apiKey - API authentication key (optional, leave empty to keep existing).
 * 
 * Note: Provider field is removed - all models use OpenAI-compatible format.
 */
export interface UpdateModelRequest {
modelId: Modelid2
name?: Name3
apiUrl?: Apiurl1
model?: Model1
inputTokenPrice?: Inputtokenprice1
outputTokenPrice?: Outputtokenprice1
provider?: Provider1
currency?: Currency1
apiKey?: Apikey1
}
/**
 * Request parameters for deleting a model configuration.
 * 
 * @property modelId - The ID of the model to delete.
 */
export interface DeleteModelRequest {
modelId: Modelid3
}
/**
 * Request parameters for selecting/switching to a model.
 * 
 * @property modelId - The ID of the model to activate.
 */
export interface SelectModelRequest {
modelId: Modelid4
}
/**
 * Request parameters for testing model connectivity.
 * 
 * @property modelId - The ID of the model to test.
 */
export interface TestModelRequest {
modelId: Modelid5
}
/**
 * Standard dashboard response with optional data payload.
 */
export interface DashboardResponse {
success: Success41
message?: Message40
error?: Error40
data?: unknown
timestamp?: Timestamp24
}
/**
 * Request parameters for retrieving LLM statistics of a specific model.
 * 
 * @property modelId - The model configuration ID.
 */
export interface GetLLMStatsByModelRequest {
modelId: Modelid6
}
/**
 * Request parameters for recording LLM usage statistics.
 * 
 * @property model - The LLM model name used.
 * @property promptTokens - Number of prompt tokens consumed.
 * @property completionTokens - Number of completion tokens consumed.
 * @property totalTokens - Total number of tokens consumed.
 * @property cost - Cost of the request (optional).
 * @property requestType - Type of request (e.g., 'summarization', 'agent', 'chat').
 */
export interface RecordLLMUsageRequest {
model: Model2
promptTokens?: Prompttokens
completionTokens?: Completiontokens
totalTokens?: Totaltokens
cost?: Cost
requestType: Requesttype
}
/**
 * Request parameters for retrieving LLM usage trend data.
 * 
 * @property dimension - Time dimension for aggregation ('day', 'week', 'month', 'custom').
 * @property days - Number of days to query when no explicit range provided (1-365).
 * @property startDate - Optional ISO datetime string marking the beginning of the range.
 * @property endDate - Optional ISO datetime string marking the end of the range.
 * @property modelConfigId - Optional model configuration ID filter.
 */
export interface GetLLMUsageTrendRequest {
dimension?: Dimension3
days?: Days1
startDate?: Startdate5
endDate?: Enddate5
modelConfigId?: Modelconfigid
}
/**
 * Dashboard trend response with dimension metadata.
 */
export interface LLMUsageTrendResponse {
success: Success42
message?: Message41
error?: Error41
data?: unknown
timestamp?: Timestamp25
dimension?: Dimension4
days?: Days2
}
/**
 * Common system operation response
 */
export interface SystemResponse {
success: Success43
message?: Message42
data?: unknown
timestamp: Timestamp26
}
/**
 * Database path response
 */
export interface DatabasePathResponse {
success: Success44
data: DatabasePathData
timestamp: Timestamp27
}
/**
 * Database path data
 */
export interface DatabasePathData {
path: Path
}
/**
 * Response for get_settings_info handler
 */
export interface GetSettingsInfoResponse {
success: Success45
message?: Message43
error?: Error42
data?: (SettingsInfoData | null)
timestamp?: Timestamp28
}
/**
 * Settings info data structure
 */
export interface SettingsInfoData {
settings: Settings
database: Database
screenshot: Screenshot
language: Language
image: Image
}
export interface Settings {
[k: string]: unknown
}
export interface Database {
[k: string]: string
}
export interface Screenshot {
[k: string]: string
}
export interface Image {
[k: string]: unknown
}
/**
 * Request parameters for updating application settings.
 * 
 * Note: LLM configuration has been migrated to multi-model management system
 * See CreateModelRequest and SelectModelRequest
 * 
 * @property databasePath - Path to the database file (optional).
 * @property screenshotSavePath - Path to save screenshots (optional).
 * @property language - Application language (zh or en) (optional).
 */
export interface UpdateSettingsRequest {
databasePath?: Databasepath
screenshotSavePath?: Screenshotsavepath
language?: Language1
}
/**
 * Update settings response
 */
export interface UpdateSettingsResponse {
success: Success46
message: Message44
timestamp: Timestamp29
}
/**
 * Response for get_image_compression_config handler
 */
export interface GetImageCompressionConfigResponse {
success: Success47
message?: Message45
error?: Error43
data?: (ImageCompressionConfigData | null)
timestamp?: Timestamp30
}
/**
 * Image compression configuration data
 */
export interface ImageCompressionConfigData {
compressionLevel?: Compressionlevel
enableRegionCropping?: Enableregioncropping
cropThreshold?: Cropthreshold
}
/**
 * Request parameters for updating image compression configuration.
 * 
 * @property compressionLevel - Compression level ('ultra', 'aggressive', 'balanced', 'quality').
 * @property enableRegionCropping - Whether to enable region-based cropping.
 * @property cropThreshold - Crop threshold percentage (0-100).
 */
export interface ImageCompressionConfigRequest {
compressionLevel?: Compressionlevel1
enableRegionCropping?: Enableregioncropping1
cropThreshold?: Cropthreshold1
}
/**
 * Response for update_image_compression_config handler
 */
export interface UpdateImageCompressionConfigResponseV2 {
success: Success48
message?: Message46
error?: Error44
data?: (ImageCompressionConfigData | null)
timestamp?: Timestamp31
}
/**
 * Response for get_image_compression_stats handler
 */
export interface GetImageCompressionStatsResponse {
success: Success49
message?: Message47
error?: Error45
data?: (ImageCompressionStatsData | null)
timestamp?: Timestamp32
}
/**
 * Image compression statistics data
 */
export interface ImageCompressionStatsData {
totalProcessed?: Totalprocessed
totalSavedBytes?: Totalsavedbytes
averageCompressionRatio?: Averagecompressionratio
}
/**
 * Response for check_initial_setup handler
 */
export interface CheckInitialSetupResponse {
success: Success50
message?: Message48
error?: Error46
data?: (InitialSetupData | null)
timestamp?: Timestamp33
}
/**
 * Initial setup check data
 */
export interface InitialSetupData {
hasModels: Hasmodels
hasActiveModel: Hasactivemodel
hasCompletedSetup: Hascompletedsetup
needsSetup: Needssetup
modelCount: Modelcount
}
/**
 * Response for complete_initial_setup handler
 */
export interface CompleteInitialSetupResponse {
success: Success51
message?: Message49
error?: Error47
data?: unknown
timestamp?: Timestamp34
}
/**
 * Request to update tray menu labels with i18n translations.
 */
export interface TrayUpdateRequest {
show: Show
hide: Hide
dashboard: Dashboard
activity: Activity
chat: Chat
agents: Agents
settings: Settings1
about: About
quit: Quit
}
/**
 * Response from tray update operation.
 */
export interface TrayUpdateResponse {
success: Success52
message?: Message50
error?: Error48
}
/**
 * Request to change tray icon visibility.
 */
export interface TrayVisibilityRequest {
visible: Visible
}
/**
 * Response from tray visibility operation.
 */
export interface TrayVisibilityResponse {
success: Success53
message?: Message51
error?: Error49
visible: Visible1
}
/**
 * A simple model representing a person.
 * 
 * @property name - The name of the person.
 */
export interface Person {
name: Name4
}
